version: '3.8'
services:
  organizr-api:
    build:
      context: ../
      dockerfile: ./docker/build/app/Dockerfile
    image: ghcr.io/cwhde/organizr-api:latest
    container_name: organizr-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"
    env_file: 
      - stack.env
    networks:
      - organizr-network

  db:
    image: mysql:8.0-debian
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - stack.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - organizr-network


networks:
  organizr-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  # Uncomment and modify the following for production use
  # driver_opts:
   #   type: none
   #   device: /path/on/host/system/data/mysql  # Specify actual host path here
   #   o: bind