version: '3.8'
services:
  organizr-api:
    build:
      context: ../
      dockerfile: ./docker/build/app/Dockerfile
    image: ghcr.io/cwhde/organizr-api:latest
    container_name: organizr-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"
    env_file: 
      - stack.env
    networks:
      - organizr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  organizr-bot:
    build:
      context: ../
      dockerfile: ./docker/build/bot/Dockerfile
    image: ghcr.io/cwhde/organizr-bot:latest
    container_name: organizr-bot
    restart: unless-stopped
    depends_on:
      organizr-api:
        condition: service_healthy
    env_file:
      - stack.env
    networks:
      - organizr-network

  db:
    image: mysql:8.0-debian
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - stack.env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 20s
      retries: 10
      start_period: 30s
    networks:
      - organizr-network

networks:
  organizr-network:
    driver: bridge

volumes:
  db_data:
    driver: local